# Generated by Django 4.1.3 on 2022-11-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('artist', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='memo',
            new_name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(default='1111-01-01'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
