# Generated by Django 4.1.3 on 2022-11-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_musictitles_rename_memo_movie_actors_movie_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='movies')),
                ('artist', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Music_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='movies')),
                ('artist', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='MusicTitles',
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(default=''),
        ),
    ]
