# Generated by Django 4.1.3 on 2022-11-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_music_content_music_data_delete_music_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_content',
            name='date',
            field=models.DateTimeField(default='9999-12-31'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(default='9999-12-31'),
        ),
    ]
