# Generated by Django 4.1.3 on 2022-11-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_music_content_date_alter_movie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='music_content',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
