# Generated by Django 4.1.3 on 2022-11-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_movie_user_alter_music_content_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music_content',
            old_name='artist',
            new_name='director',
        ),
    ]
