# Generated by Django 4.2.6 on 2023-10-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_artist_music_content_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='music_content',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
